on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.ziainnovation.com
        username: test_git@git.ziainnovation.com
        password: ${{ secrets.PASSWORD }}
        protocol: ftps
        port: 21
        server-dir: git.ziainnovation.com/
       
       